---
name: Build site and lint code blocks

on: push

jobs:
  build-site:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install PyYAML
        run: pip install PyYAML

      - name: Lint YAML files
        working-directory: ./tests
        run: python yaml-validator.py --directory ../content --extension .md

  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Lint JSON files
        working-directory: ./tests
        run: python json-validator.py --directory ../content --extension .md
